require "user.autocommands"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.treesitter"
require "user.gitsigns"
require "user.nvim-tree"
require "user.lualine"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.nerdcommenter"
require "user.telescope"
require "user.whichkey"
--require("user.telescope").load_extension('fzf')
-- require "user.bufferline"
-- require "user.airline"
